---

- hosts: all
  gather_facts: False


  tasks:

    - name: Update the apt registry
      become: yes
      raw: apt update -y

    - name: Update CA Certs
      become: yes
      apt: pkg=ca-certificates state=installed update_cache=true

    - name: Create tooling directory for rest of the scripts
      file:
        path: tools
        state: directory
        mode: 0755


    - name: Installs Git
      become: yes
      apt:
        pkg: git,build-essential,curl,file,linuxbrew-wrapper
        state: present
        update_cache: true

    - name: Installs apt packages Part 1
      become: yes
      apt:
        pkg: vim,thefuck,git,fish,neovim,ripgrep,mlocate
        state: present
        update_cache: true

    - name: Installs apt packages part 2
      become: yes
      apt:
        pkg: build-essential,curl,file,linuxbrew-wrapper,homesick
        state: installed
        update_cache: true


    - name: Installs OMF "oh my fish"
      get_url:
        url: "https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install"
        dest: "tools/omf.install"

    - name: Install Oh my fish
      shell: fish tools/omf.install --noninteractive

    # - name: set fish as default shell
    #   shell: chsh -s /root/bin/fish

    - name: Install homebrew dependencies
      homebrew:
        name: fzf,z,black
        state: latest

    # # - name: Install thefuck with Omf
    # #   raw: omf install thefuck

    - name: Build locate database
      shell: sudo updatedb
