---

- hosts: all
  become: yes
  gather_facts: False


  tasks:

    - name: Update the apt registry
      raw: apt update -y

    - name: Update CA Certs
      apt: pkg=ca-certificates state=installed update_cache=true

    - name: Create tooling directory for rest of the scripts
      file:
        path: tools
        state: directory
        mode: 0755

    - name: Installs Vim
      apt:
        pkg: vim
        state: present
        update_cache: true

    - name: Installs thefuck web server
      apt:
        pkg: thefuck
        state: installed
        update_cache: true

    - name: Inserting a line after a pattern in Ansible example
      lineinfile:
        path: ~/.bashrc
        line: |
          eval $(thefuck --alias)
          eval $(thefuck --alias FUCK)

    - name: Installs Z
      get_url:
        url: "https://raw.githubusercontent.com/rupa/z/master/z.sh"
        dest: "tools/z.sh"

    - name: Installs Fish
      apt:
        pkg: fish
        state: installed
        update_cache: true

    - name: Installs Rip Grep
      apt:
        pkg: ripgrep 
        state: installed
        update_cache: true

    - name: Installs Neovim
      apt:
        pkg: neovim
        state: installed
        update_cache: true

    - name: Installs Homesick
      apt:
        pkg: homesick
        state: installed
        update_cache: true

    - name: Installs Locate
      apt:
        pkg: mlocate
        state: installed
        update_cache: true

    - name: Installs OMF "oh my fish"
      get_url:
        url: "https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install"
        dest: "tools/omf.install"

    - name: Install Oh my fish
      shell: fish tools/omf.install --noninteractive

    - name: set fish as default shell
      shell: chsh -s /root/bin/fish

    # - name: Make fish run?!
    #   raw: ps aux | grep fish

    # - name: Install thefuck with Omf
    #   raw: omf install thefuck

    - name: Installs Git
      apt:
        pkg: git
        state: installed
        update_cache: true

    - name: Build locate database
      shell: sudo updatedb
