---

- hosts: all
  become: yes
  gather_facts: False


  tasks:
    - name: Update CA Certs
      apt: pkg=ca-certificates state=installed update_cache=true

    - name: Create tooling directory for rest of the scripts
      file:
        path: tools
        state: directory
        mode: 0755

    - name: Update the apt registry
      raw: apt update -y

    - name: Installs Vim
      apt:
        pkg: vim
        state: present
        update_cache: true

    - name: Installs thefuck
      apt: pkg=thefuck state=installed update_cache=true

    - name: Inserting a line after a pattern in Ansible example
      lineinfile:
        dest: ~/.bashrc
        state: present
        regexp: fuck
        line: |
          eval $(thefuck --alias)
          eval $(thefuck --alias FUCK)

    - name: Installs Rip Grep
      apt: pkg=ripgrep state=installed update_cache=true


    - name: Installs Neovim
      apt: pkg=neovim state=installed update_cache=true

    - name: Installs Locate
      apt: pkg=mlocate state=installed update_cache=true

    - name: Installs Homesick
      apt: pkg=homesick state=installed update_cache=true


    - name: Installs Z
      get_url:
        url: "https://raw.githubusercontent.com/rupa/z/master/z.sh"
        dest: "tools/z.sh"

    - name: Activation of z for bash
      lineinfile:
        dest: /root/.bashrc
        line: 'tools/z.sh'
        regexp: 'z\.sh'
        owner: root
        group: root
        mode: 0644


    - name: Installs OMF "oh my fish"
      get_url:
          url: "https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install"
          dest: "tools/omf.install"

    - name: Run Fish install and omf install
      apt:
        pkg: fish
        state: installed
        update_cache: true


          # - name: set fish as default shell
          # shell: chsh -s /root/bin/fish


          #     - name: Installs Git
          #       apt: pkg=git state=installed update_cache=true

          # - name: Make fish run?!
          #   raw: ps aux | grep fish

          #- name: Install Z with Omf
          #  shell: omf install z

          #- name: Install Zish with Omf
          #  shell: omf install zish

          #- name: Install NVM
          #  shell: apt install nvm

          #- name: Install thefuck with Omf
          #  shell: omf install thefuck

          #- name: Install pipenv
          #  shell: apt install pipenv

    - name: Build locate database
      raw: sudo updatedb
