- hosts: aws


  vars:
    ansible_ssh_private_key_file: ~/.ssh/cekey.pem

  tasks:

    - name: Download aws via Ansible
      get_url:
        url: https://mathias-kettner.de/support/1.5.0p13/check-mk-raw-1.5.0p13-el7-38.x86_64.rpm
        dest: /tmp/aws.deb

