---
- hosts: packer
  become: yes

  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  tasks:

    - name: Download packer via Ansible
      get_url:
        url: https://releases.hashicorp.com/packer/1.3.5/packer_1.3.5_linux_amd64.zip
        dest: /tmp/packer.deb

#build docker image in packer